// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRPodVlR7gKYmVAZEIg8Wca5_zXr6m0c',
    appId: '1:915479593997:web:a4ccc525b94f4fad064144',
    messagingSenderId: '915479593997',
    projectId: 'flutter-app-bdb44',
    authDomain: 'flutter-app-bdb44.firebaseapp.com',
    storageBucket: 'flutter-app-bdb44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjXWw7K-jVjU1tWxIMK-nydbQ1OzfdKrY',
    appId: '1:915479593997:android:05e2f555d7e8699b064144',
    messagingSenderId: '915479593997',
    projectId: 'flutter-app-bdb44',
    storageBucket: 'flutter-app-bdb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcc4IM7tZ5uOnxmHVXxXfFyudq85wsnbo',
    appId: '1:915479593997:ios:3466239ef66fd7bc064144',
    messagingSenderId: '915479593997',
    projectId: 'flutter-app-bdb44',
    storageBucket: 'flutter-app-bdb44.firebasestorage.app',
    iosBundleId: 'com.example.webboradkakkak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcc4IM7tZ5uOnxmHVXxXfFyudq85wsnbo',
    appId: '1:915479593997:ios:3466239ef66fd7bc064144',
    messagingSenderId: '915479593997',
    projectId: 'flutter-app-bdb44',
    storageBucket: 'flutter-app-bdb44.firebasestorage.app',
    iosBundleId: 'com.example.webboradkakkak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgRPodVlR7gKYmVAZEIg8Wca5_zXr6m0c',
    appId: '1:915479593997:web:5021be8669a10360064144',
    messagingSenderId: '915479593997',
    projectId: 'flutter-app-bdb44',
    authDomain: 'flutter-app-bdb44.firebaseapp.com',
    storageBucket: 'flutter-app-bdb44.firebasestorage.app',
  );
}
